Wiki/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Wiki.Models;
using Wiki.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace Wiki.Controllers
{
    public class CommentController : Controller
    {
        ВикисловарьContext db;

        public CommentController(ВикисловарьContext context)
        {
            db = context;
        }

        public IActionResult New(CommentableViewModel model)
        {
            Комментарий comment = new Комментарий
            {
                IdПравки = model.IdПравки,
                ТекстКомментария = model.ТекстКомментария,
                IdПользователя = new Guid(User.Claims.FirstOrDefault(c => c.Type == "Id").Value),
                ВремяНаписания = DateTime.Now
            };

            db.Комментарий.Add(comment);
            db.SaveChanges();

            return Redirect(model.ПредыдущийАдрес);
        }
    }
}

Wiki/Controllers/EditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Wiki.Models;
using Wiki.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace Wiki.Controllers
{
    [Authorize(Roles = "Пользователь, Модератор")]
    public class EditController : Controller
    {
        ВикисловарьContext db;

        public EditController(ВикисловарьContext context)
        {
            db = context;
        }

        public IActionResult Index(Guid edit_id)
        {
            var editQuery = (from e in db.Правка
                             where e.IdПравки == edit_id
                             select e).Include(e => e.КодЧастиРечиNavigation)
                       .Include(e => e.КодСтатусаNavigation).Include(e => e.IdСтатьиNavigation)
                       .ThenInclude(a => a.СловарнаяСтатьяТег).ThenInclude(t => t.КодТегаNavigation);
            Правка edit = editQuery.FirstOrDefault();

            if (edit != null)
            {
                var comments = (from c in db.Комментарий
                                where c.IdПравки == edit.IdПравки
                                orderby c.ВремяНаписания
                                select c).Include(c => c.IdПользователяNavigation)
                                .ThenInclude(u => u.КодКатегорииNavigation).ToList();
                EditViewViewModel model = new EditViewViewModel
                {
                    Правка = edit,
                    ВсеКомментарии = comments,
                    ПредыдущийАдрес = Url.RouteUrl(new { controller = "Edit", action = "Index", edit_id = edit_id })
                };
                return View(model);
            }

            return RedirectToAction("Index", "Home");
        }

        public IActionResult ViewAll()
        {
            Guid user_id = new Guid(User.Claims.FirstOrDefault(c => c.Type == "Id").Value);

            ICollection<Правка> userEdits = (from e in db.Правка
                                             where e.IdПользователя == user_id
                                             select e).Include(e => e.КодСтатусаNavigation).ToList();

            userEdits = userEdits.OrderByDescending(e => e.ДатаИзмененияСтатуса).ToList();

            EditViewAllViewModel model = new EditViewAllViewModel { ВсеПравки = userEdits };

            return View(model);
        }

        [HttpGet]
        public IActionResult New(Guid article_id)
        {
            var articleQuery = (from a in db.СловарнаяСтатья
                                where a.IdСтатьи == article_id
                                select a).Include(a => a.СловарнаяСтатьяТег).ThenInclude(t => t.КодТегаNavigation).Include(s => s.IdСловаNavigation);
            СловарнаяСтатья article = articleQuery.FirstOrDefault();

            if (article != null)
            {
                ViewBag.allPartsOfSpeech = new SelectList(db.ЧастьРечи.ToList(), "КодЧастиРечи", "Название");

                ArticleEditViewModel articleEditViewModel = new ArticleEditViewModel
                {
                    IdСтатьи = article.IdСтатьи,
                    Название = article.Название,
                    ТекстСтатьи = article.ТекстСтатьи,
                    СловарнаяСтатьяТег = article.СловарнаяСтатьяТег,
                    КодЧастиРечи = article.КодЧастиРечи
                };

                return View(articleEditViewModel);
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult New(ArticleEditViewModel articleEditViewModel)
        {
            if (ModelState.IsValid)
            {
                СтатусПравки unseen = db.СтатусПравки.FirstOrDefault(s => s.Название == "Не проверено");
                Правка edit = new Правка
                {
                    ДатаСоздания = DateTime.Now,
                    Название = articleEditViewModel.Название,
                    ТекстСтатьи = articleEditViewModel.ТекстСтатьи,
                    ДатаИзмененияСтатуса = DateTime.Now,
                    IdСтатьи = articleEditViewModel.IdСтатьи,
                    IdПользователя = new Guid(User.Claims.FirstOrDefault(c => c.Type == "Id").Value),
                    КодЧастиРечи = articleEditViewModel.КодЧастиРечи,
                    КодСтатуса = unseen.КодСтатуса
                };

                db.Правка.Add(edit);
                db.SaveChanges();

                return RedirectToAction("ViewAll", "Edit");
            }
            return View(articleEditViewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Модератор")]
        public IActionResult Check(Guid edit_id)
        {
            var editQuery = (from e in db.Правка
                             where e.IdПравки == edit_id
                             select e).Include(e => e.КодЧастиРечиNavigation)
                       .Include(e => e.КодСтатусаNavigation).Include(e => e.IdСтатьиNavigation)
                       .ThenInclude(a => a.СловарнаяСтатьяТег).ThenInclude(t => t.КодТегаNavigation);
            Правка edit = editQuery.FirstOrDefault();

            if (edit != null)
            {
                var comments = (from c in db.Комментарий
                                where c.IdПравки == edit.IdПравки
                                orderby c.ВремяНаписания
                                select c).Include(c => c.IdПользователяNavigation)
                                .ThenInclude(u => u.КодКатегорииNavigation).ToList();

                ViewBag.allStatuses = new SelectList(db.СтатусПравки.Where(s => s.Название!="Не проверено").ToList(), "КодСтатуса", "Название");

                EditCheckViewModel model = new EditCheckViewModel
                {
                    Правка = edit,
                    ВсеКомментарии = comments,
                    ПредыдущийАдрес = Url.RouteUrl(new { controller = "Edit", action = "Check", edit_id = edit_id }),
                    КодСтатуса = edit.КодСтатуса
                };
                return View(model);
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [Authorize(Roles = "Модератор")]
        public IActionResult Check(EditCheckViewModel model)
        {
            Правка edit = db.Правка.FirstOrDefault(e => e.IdПравки == model.IdПравки);
            Guid user_id = new Guid(User.Claims.FirstOrDefault(c => c.Type == "Id").Value);
            НазначенныйМодератор moderator = (from nm in db.НазначенныйМодератор
                                              where nm.IdСтатьи == edit.IdСтатьи && nm.IdПользователя == user_id
                                              select nm).FirstOrDefault();

            ICollection<СтатусПравки> statuses = db.СтатусПравки.ToList();
            long notChecked = statuses.FirstOrDefault(s => s.Название == "Не проверено").КодСтатуса;
            long approved = statuses.FirstOrDefault(s => s.Название == "Принято").КодСтатуса;

            if (moderator!=null && model.КодСтатуса!=notChecked)
            {
                СловарнаяСтатья article = db.СловарнаяСтатья.FirstOrDefault(e => e.IdСтатьи == edit.IdСтатьи);

                if (model.КодСтатуса == approved)
                {
                    article.СтатьяГотова = true;
                    article.КодЧастиРечи = edit.КодЧастиРечи;
                    article.ТекстСтатьи = edit.ТекстСтатьи;

                    db.СловарнаяСтатья.Update(article);
                }
                else if (model.КодСтатуса!=approved&&edit.КодСтатуса==approved)
                {

                    var lastEdits = db.Правка.Where(e => e.IdСтатьи==edit.IdСтатьи&&e.КодСтатуса==approved).OrderByDescending(e => e.ДатаИзмененияСтатуса).ToList();

                    if (lastEdits.Count>1)
                    {
                        article.КодЧастиРечи = lastEdits[1].КодЧастиРечи;
                        article.ТекстСтатьи = lastEdits[1].ТекстСтатьи;

                        db.СловарнаяСтатья.Update(article);
                    }
                    else
                    {
                        article.СтатьяГотова = false;
                        article.ТекстСтатьи = "Статья в разработке";
                        article.КодЧастиРечи = 12;
                        db.СловарнаяСтатья.Update(article);
                    }
                }

                edit.IdНазначенногоМодератора = moderator.IdНазначенногоМодератора;
                edit.ДатаИзмененияСтатуса = DateTime.Now;
                edit.КодСтатуса = model.КодСтатуса;
                db.Правка.Update(edit);

                db.SaveChanges();
            }

            return RedirectToAction("CheckAll", "Edit");
        }

        [Authorize(Roles = "Модератор")]
        public IActionResult CheckAll()
        {
            Guid user_id = new Guid(User.Claims.FirstOrDefault(c => c.Type == "Id").Value);

            ICollection<НазначенныйМодератор> moderators = (from nm in db.НазначенныйМодератор
                                                            where nm.IdПользователя == user_id
                                                            select nm).Include(nm => nm.IdСтатьиNavigation)
                                                            .ThenInclude(a => a.Правка).ToList();

            ICollection<Правка> moderatedEdits = (from e in db.Правка
                                                  where e.IdНазначенногоМодератораNavigation.IdПользователя == user_id
                                                  select e).Include(e => e.КодСтатусаNavigation).ToList();

            List<Правка> forCheck = new List<Правка>();
            long notChecked = db.СтатусПравки.FirstOrDefault(s => s.Название == "Не проверено").КодСтатуса;

            foreach (var mod in moderators)
            {
                var edits = mod.IdСтатьиNavigation.Правка.Where(e => e.КодСтатуса==notChecked).ToList();

Wiki/Views/Edit/Check.cshtml
@model Wiki.ViewModels.EditCheckViewModel
@{
    ViewData["Title"] = "Check";
}

<div class="row" style="min-height: 5vh"></div>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="row">
            <div class="col-md-3">
                <h4>
                    Статус:
                </h4>
            </div>
            <div class="col-md-3">
                <h4>
                    @switch (Model.Правка.КодСтатуса)
                    {
                        case 0:
                            <span class="tag tag-info">@Model.Правка.КодСтатусаNavigation.Название</span>
                            break;
                        case 1:
                            <span class="tag tag-warning">@Model.Правка.КодСтатусаNavigation.Название</span>
                            break;
                        case 2:
                            <span class="tag tag-success">@Model.Правка.КодСтатусаNavigation.Название</span>
                            break;
                        case 3:
                            <span class="tag tag-danger">@Model.Правка.КодСтатусаNavigation.Название</span>
                            break;
                    }
                </h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <h4>
                    Название:
                </h4>
            </div>
            <div class="col-md-3">
                <h4>
                    @Model.Правка.Название
                </h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3"><h4>Теги: </h4></div>
            <div class="col-md-9 visible-md-inline">
                <h4>
                    @foreach (var tag in Model.Правка.IdСтатьиNavigation.СловарнаяСтатьяТег)
                    {
                        <span class="tag tag-default">@tag.КодТегаNavigation.Название</span>
                    }
                </h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <h4>
                    Часть речи:
                </h4>
            </div>
            <div class="col-md-9">
                <h4><span class="tag tag-primary">@Model.Правка.КодЧастиРечиNavigation.Название</span></h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p class="lead">
                    @Model.Правка.ТекстСтатьи
                </p>
            </div>
        </div>
        <div class="row">
            <form asp-controller="Edit" asp-action="Check" method="post">
                <input asp-for="IdПравки" type="hidden" value="@Model.Правка.IdПравки" />
                <div class="form-inline">
                    <div class="form-group pull-xs-right">
                            <select asp-for="КодСтатуса" asp-items="ViewBag.allStatuses" class="form-control"></select>
                            <input type="submit" value="Сохранить" class="btn btn-outline-primary" />
                    </div>
                </div>
            </form>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-3">
                <h4>Комментарии</h4>
            </div>
        </div>
        <div class="row">
            @foreach (var comment in Model.ВсеКомментарии)
            {
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-block">
                            <div class="row">
                                <div class="col-md-4">
                                    <span>@comment.IdПользователяNavigation.КодКатегорииNavigation.Название</span>
                                </div>
                                <div class="col-md-8">
                                    <div style="text-align: right">
                                        @comment.ВремяНаписания
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <h4 class="card-title">
                                        @comment.IdПользователяNavigation.Фамилия @comment.IdПользователяNavigation.Имя @comment.IdПользователяNavigation.Отчество
                                    </h4>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <p class="card-text">
                                        @comment.ТекстКомментария
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="row">
            <form asp-controller="Comment" asp-action="New" method="post">
                <input asp-for="IdПравки" type="hidden" value="@Model.Правка.IdПравки" />
                <input asp-for="ПредыдущийАдрес" type="hidden" value="@Model.ПредыдущийАдрес" />
                <textarea class="form-control" rows="4" asp-for="ТекстКомментария"></textarea>
                <div class="row" style="min-height: 1vh"></div>
                <div class="pull-xs-right">
                    <input type="submit" value="Отправить комментарий" class="btn btn-outline-primary" />
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>

Wiki/Views/Edit/CheckAll.cshtml
@model Wiki.ViewModels.EditCheckAllViewModel
@{
    ViewData["Title"] = "CheckAll";
}

<div class="row" style="min-height: 5vh"></div>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="row">
            <div class="col-md-3">
                <h2>
                    Правки на проверку:
                </h2>
            </div>
        </div>
        @foreach (var edit in Model.ПравкиНаПроверку)
        {
            <div class="row">
                <div class="col-md-3"><a asp-controller="Edit" asp-action="Check" asp-route-edit_id="@edit.IdПравки">@edit.Название</a></div>
                <div class="col-md-3">
                    @switch (edit.КодСтатуса)
                    {
                        case 0:
                            <span class="tag tag-info">@edit.КодСтатусаNavigation.Название</span>
                            break;
                        case 1:
                            <span class="tag tag-warning">@edit.КодСтатусаNavigation.Название</span>
                            break;
                        case 2:
                            <span class="tag tag-success">@edit.КодСтатусаNavigation.Название</span>
                            break;
                        case 3:
                            <span class="tag tag-danger">@edit.КодСтатусаNavigation.Название</span>
                            break;
                    }
                </div>
                <div class="col-md-3"><span>@edit.ДатаИзмененияСтатуса.ToShortDateString()</span></div>
            </div>
        }
        <hr />
        <div class="row">
            <div class="col-md-3">
                <h2>
                    Проверенные правки:
                </h2>
            </div>
        </div>
        @foreach (var edit in Model.ПровененныеПравки)
        {
            <div class="row">
                <div class="col-md-3"><a asp-controller="Edit" asp-action="Check" asp-route-edit_id="@edit.IdПравки">@edit.Название</a></div>
                <div class="col-md-3">
                    @switch (edit.КодСтатуса)
                    {
                        case 0:
                            <span class="tag tag-info">@edit.КодСтатусаNavigation.Название</span>
                            break;
                        case 1:
                            <span class="tag tag-warning">@edit.КодСтатусаNavigation.Название</span>
                            break;
                        case 2:
                            <span class="tag tag-success">@edit.КодСтатусаNavigation.Название</span>
                            break;
                        case 3:
                            <span class="tag tag-danger">@edit.КодСтатусаNavigation.Название</span>
                            break;
                    }
                </div>
                <div class="col-md-3"><span>@edit.ДатаИзмененияСтатуса.ToShortDateString()</span></div>
            </div>
        }
    </div>
    <div class="col-md-1"></div>
</div>

Wiki/Views/Edit/Index.cshtml
@model Wiki.ViewModels.EditViewViewModel
@{
    ViewData["Title"] = "View";
}

<div class="row" style="min-height: 5vh"></div>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="row">
            <div class="col-md-3">
                <h4>
                    Статус:
                </h4>
            </div>
            <div class="col-md-3">
                <h4>
                    @switch (Model.Правка.КодСтатуса)
                    {
                        case 0:
                            <span class="tag tag-info">@Model.Правка.КодСтатусаNavigation.Название</span>
                            break;
                        case 1:
                            <span class="tag tag-warning">@Model.Правка.КодСтатусаNavigation.Название</span>
                            break;
                        case 2:
                            <span class="tag tag-success">@Model.Правка.КодСтатусаNavigation.Название</span>
                            break;
                        case 3:
                            <span class="tag tag-danger">@Model.Правка.КодСтатусаNavigation.Название</span>
                            break;
                    }
                </h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <h4>
                    Название:
                </h4>
            </div>
            <div class="col-md-3">
                <h4>
                    @Model.Правка.Название
                </h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3"><h4>Теги: </h4></div>
            <div class="col-md-9 visible-md-inline">
                <h4>
                    @foreach (var tag in Model.Правка.IdСтатьиNavigation.СловарнаяСтатьяТег)
                    {
                        <span class="tag tag-default">@tag.КодТегаNavigation.Название</span>
                    }
                </h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <h4>
                    Часть речи:
                </h4>
            </div>
            <div class="col-md-9">
                <h4><span class="tag tag-primary">@Model.Правка.КодЧастиРечиNavigation.Название</span></h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p class="lead">
                    @Model.Правка.ТекстСтатьи
                </p>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-3">
                <h4>Комментарии</h4>
            </div>
        </div>
        <div class="row">
            @foreach (var comment in Model.ВсеКомментарии)
            {
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-block">
                            <div class="row">
                                <div class="col-md-4">
                                    <span>@comment.IdПользователяNavigation.КодКатегорииNavigation.Название</span>
                                </div>
                                <div class="col-md-8">
                                    <div style="text-align: right">
                                        @comment.ВремяНаписания
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <h4 class="card-title">
                                        @comment.IdПользователяNavigation.Фамилия @comment.IdПользователяNavigation.Имя @comment.IdПользователяNavigation.Отчество
                                    </h4>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <p class="card-text">
                                        @comment.ТекстКомментария
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="row">
            <form asp-controller="Comment" asp-action="New" method="post">
                <input asp-for="IdПравки" type="hidden" value="@Model.Правка.IdПравки" />
                <input asp-for="ПредыдущийАдрес" type="hidden" value="@Model.ПредыдущийАдрес" />
                <textarea class="form-control" rows="4" asp-for="ТекстКомментария"></textarea>
                <div class="row" style="min-height: 1vh"></div>
                <div class="pull-xs-right">
                    <input type="submit" value="Отправить комментарий" class="btn btn-outline-primary" />
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>

Wiki/Views/Edit/New.cshtml
@model Wiki.ViewModels.ArticleEditViewModel

<div class="row" style="min-height: 5vh"></div>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <form asp-action="New" asp-controller="Edit" asp-anti-forgery="true">
            <div class="validation" asp-validation-summary="ModelOnly" />
            <div class="row">
                    <h2>
                        Правка статьи
                    </h2>
            </div>
            <div class="row">
                <div class="col-md-3"><h4><label asp-for="Название">Название:</label></h4></div>
                <div class="col-md-9">
                    <h4>
                        @Model.Название
                    </h4>
                </div>
                <input asp-for="Название" type="hidden" value="@Model.Название" />
                <input asp-for="IdСтатьи" type="hidden" value="@Model.IdСтатьи" />
            </div>
            <div class="row">
                <div class="col-md-3"><h4><label asp-for="СловарнаяСтатьяТег">Теги:</label></h4></div>
                <div class="col-md-9">
                    <h4>
                        @foreach (var tag in Model.СловарнаяСтатьяТег)
                        {
                            <span class="tag tag-default">@tag.КодТегаNavigation.Название</span>
                        }
                    </h4>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <h4>
                        <label asp-for="КодЧастиРечи">Выберите часть речи: </label>
                    </h4>
                </div>
                <div class="col-md-6">
                    <h4><select asp-for="КодЧастиРечи" asp-items="ViewBag.allPartsOfSpeech" class="form-control"></select></h4>
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="row">
                <div class="cal-md-12">
                    <h4><label asp-for="ТекстСтатьи">Редактируйте текст статьи</label></h4>
                    <textarea asp-for="ТекстСтатьи" value="@Model.ТекстСтатьи" rows="5" class="form-control"></textarea>
                </div>
            </div>
            <div class="row" style="min-height: 1vh"></div>
            <div class="pull-xs-right">
                <input type="submit" value="Отправить на проверку" class="btn btn-outline-primary" />
            </div>
        </form>
        <div class="col-md-1"></div>
    </div>
</div>

Wiki/Views/Edit/ViewAll.cshtml
@model Wiki.ViewModels.EditViewAllViewModel
@{
    ViewData["Title"] = "ViewAll";
}


<div class="row" style="min-height: 5vh"></div>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="row">
            <div class="col-md-3">
                <h2>
                    Мои правки:
                </h2>
            </div>
        </div>
        @foreach (var edit in Model.ВсеПравки)
        {
            <div class="row">
                <div class="col-md-3"><a asp-controller="Edit" asp-action="Index" asp-route-edit_id="@edit.IdПравки">@edit.Название</a></div>
                <div class="col-md-3">
                    @switch (edit.КодСтатуса)
                    {
                        case 0:
                            <span class="tag tag-info">@edit.КодСтатусаNavigation.Название</span>
                            break;
                        case 1:
                            <span class="tag tag-warning">@edit.КодСтатусаNavigation.Название</span>
                            break;
                        case 2:
                            <span class="tag tag-success">@edit.КодСтатусаNavigation.Название</span>
                            break;
                        case 3:
                            <span class="tag tag-danger">@edit.КодСтатусаNavigation.Название</span>
                            break;
                    }
                </div>
                <div class="col-md-3"><span>@edit.ДатаИзмененияСтатуса.ToShortDateString()</span></div>
            </div>
        }
    </div>
    <div class="col-md-1"></div>
</div>