Wiki/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Wiki.Models;
using Wiki.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Wiki.Controllers
{
    public class ArticleController : Controller
    {
        ВикисловарьContext db;

        public ArticleController(ВикисловарьContext context)
        {
            db = context;
        }

        public IActionResult Index(Guid article_id)
        {
            var articleQuery = (from a in db.СловарнаяСтатья
                          where a.IdСтатьи== article_id
                                select a).Include(a => a.КодЧастиРечиNavigation).Include(a => a.СловарнаяСтатьяТег).ThenInclude(t => t.КодТегаNavigation);
            СловарнаяСтатья article = articleQuery.FirstOrDefault();

            if (article!=null)
            {
                return View(article);
            }

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Пользователь, Модератор")]
        [HttpGet]
        public IActionResult New(string name)
        {
            ArticleNewViewModel model = new ArticleNewViewModel
            {
                Название = name
            };
            ViewBag.allPartsOfSpeech = new SelectList(db.ЧастьРечи.ToList(), "КодЧастиРечи", "Название");

            return View(model);
        }

        [Authorize(Roles = "Пользователь, Модератор")]
        [HttpPost]
        public IActionResult New(ArticleNewViewModel model)
        {
            Слово word = db.Слово.FirstOrDefault(w => model.Название.Contains(w.Название));
            if (word==null)
            {
                word = new Слово { Название=model.Название, IdСлова = Guid.NewGuid() };
                db.Слово.Add(word);
            }

            List<string> tags = model.СтрокаТегов.Split('#').ToList();
            List<Тег> objectTags = new List<Тег>();

            for (int i = 0;i<tags.Count;i++)
            {
                tags[i] = tags[i].Replace("#", "");
                tags[i] = tags[i].Replace(" ", "");
                if (tags[i]!="")
                {
                    Тег foundTag = db.Тег.FirstOrDefault(t => t.Название == tags[i]);
                    if (foundTag==null)
                    {
                        foundTag = new Тег { Название= tags[i], КодТега = db.Тег.ToList().Count};
                        db.Тег.Add(foundTag);
                    }
                    objectTags.Add(foundTag);
                }
            }
            
            СловарнаяСтатья article = new СловарнаяСтатья
            {
                Название = model.Название,
                СтатьяГотова = false,
                IdСлова = word.IdСлова,
                IdСтатьи = Guid.NewGuid()
            };

            db.СловарнаяСтатья.Add(article);

            foreach (Тег tag in objectTags)
            {
                СловарнаяСтатьяТег articleTag = new СловарнаяСтатьяТег { IdСтатьи = article.IdСтатьи, КодТега = tag.КодТега };
                db.СловарнаяСтатьяТег.Add(articleTag);
            }

            Правка edit = new Правка
            {
                ТекстСтатьи = model.ТекстСтатьи,
                Название = model.Название,
                КодЧастиРечи = model.КодЧастиРечи,
                IdСтатьи = article.IdСтатьи,
                ДатаСоздания = DateTime.Now,
                ДатаИзмененияСтатуса = DateTime.Now,
                IdПользователя = new Guid(User.Claims.FirstOrDefault(c => c.Type == "Id").Value)
            };

            db.Правка.Add(edit);
            db.SaveChanges();

            return RedirectToAction("ViewAll", "Edit");
        }
    }
}

Wiki/Views/Article/Index.cshtml
@model Wiki.СловарнаяСтатья
@{
    ViewData["Title"] = "View";
}

<div class="row" style="min-height: 5vh"></div>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="row">
            <div class="col-md-2">
                <h2>
                    @Model.Название
                </h2>
            </div>
            <div class="col-md-10" style="text-align: right">
                <a asp-controller="Edit" asp-action="New" asp-route-article_id="@Model.IdСтатьи">[править статью]</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3"><h4>Теги: </h4></div>
            <div class="col-md-9">
                <h4>
                    @foreach (var tag in Model.СловарнаяСтатьяТег)
                    {
                        <span class="tag tag-default">@tag.КодТегаNavigation.Название</span>
                    }
                </h4>
            </div>
        </div>
        @if (Model.СтатьяГотова)
        {
            <div class="row">
                <div class="col-md-3">
                    <h4>
                        Часть речи:
                    </h4>
                </div>
                <div class="col-md-9">
                    <h4><span class="tag tag-primary">@Model.КодЧастиРечиNavigation.Название</span></h4>
                </div>
            </div>
        }
        <div class="row">
            <div class="col-md-12">
                <p class="lead">
                    @Model.ТекстСтатьи
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>

Wiki/Views/Article/New.cshtml
@model Wiki.ViewModels.ArticleNewViewModel
@{
    ViewData["Title"] = "New";
}

<div class="row" style="min-height: 5vh"></div>
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <form asp-action="New" asp-controller="Article" asp-anti-forgery="true">
            <div class="validation" asp-validation-summary="ModelOnly" />
            <div class="row">
                <h2>
                    Создать статью
                </h2>
            </div>
            <div class="row">
                <div class="col-md-3"><h4><label asp-for="Название">Название:</label></h4></div>
                <div class="col-md-6">
                    <input asp-for="Название" type="text" value="@Model.Название" class="form-control" />
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="row">
                <div class="col-md-3"><h4><label asp-for="СтрокаТегов">Теги:</label></h4></div>
                <div class="col-md-6">
                    <input asp-for="СтрокаТегов" type="text" class="form-control" />
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <h4>
                        <label asp-for="КодЧастиРечи">Выберите часть речи: </label>
                    </h4>
                </div>
                <div class="col-md-6">
                    <h4><select asp-for="КодЧастиРечи" asp-items="ViewBag.allPartsOfSpeech" class="form-control"></select></h4>
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="row">
                <div class="cal-md-12">
                    <h4><label asp-for="ТекстСтатьи">Текст статьи</label></h4>
                    <textarea asp-for="ТекстСтатьи" value="@Model.ТекстСтатьи" rows="5" class="form-control"></textarea>
                </div>
            </div>
            <div class="row" style="min-height: 1vh"></div>
            <div class="pull-xs-right">
                <input type="submit" value="Отправить на проверку" class="btn btn-outline-primary" />
            </div>
        </form>
        <div class="col-md-1"></div>
    </div>
</div>